trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: continious_integration
  displayName: Continious Integration
  jobs:
  - job: build
    displayName: Build
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: dotnet --version
      displayName: Check .Net version
    - script: dotnet restore
      displayName: Restore Nuget
    - script: dotnet build
      displayName: Build .Net project
    - script: dotnet run
      displayName: Run .Net project
